name: GeOsm

on:
  pull_request:
    branches: ['main', 'dev']
    paths-ignore: ['docs/**']

  push:
    branches: ['main', 'dev']
    paths-ignore: ['docs/**']

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install && npm run build

      - name: Pretty
        run: npm run pretty-quick

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test
